# Generated by Django 5.2.6 on 2025-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Photo')),
            ],
        ),
    ]
